// <auto-generated />
using System;
using EFCoreSample2.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreSample2.Migrations
{
    [DbContext(typeof(EF6Sample1MyContextContext))]
    partial class EF6Sample1MyContextContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreSample2.Model.Articles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("SizeDescription");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("EFCoreSample2.Model.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EFCoreSample2.Model.OrderArticles", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnName("Order_Id");

                    b.Property<int>("ArticleId")
                        .HasColumnName("Article_Id");

                    b.HasKey("OrderId", "ArticleId");

                    b.HasIndex("ArticleId")
                        .HasName("IX_Article_Id");

                    b.HasIndex("OrderId")
                        .HasName("IX_Order_Id");

                    b.ToTable("OrderArticles");
                });

            modelBuilder.Entity("EFCoreSample2.Model.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnName("Customer_Id");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasName("IX_Customer_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EFCoreSample2.Model.OrderArticles", b =>
                {
                    b.HasOne("EFCoreSample2.Model.Articles", "Article")
                        .WithMany("OrderArticles")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("FK_dbo.OrderArticles_dbo.Articles_Article_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EFCoreSample2.Model.Orders", "Order")
                        .WithMany("OrderArticles")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_dbo.OrderArticles_dbo.Orders_Order_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCoreSample2.Model.Orders", b =>
                {
                    b.HasOne("EFCoreSample2.Model.Customers", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_dbo.Orders_dbo.Customers_Customer_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
